import a from '../images/a.jpg';
import b from '../images/b.jpg';
import c from '../images/c.jpg';
import d from '../images/d.jpg';
import e from '../images/e.jpg';
import g from '../images/g.jpg';
import i from '../images/i.jpg';
import j from '../images/j.jpg';
import k from '../images/k.jpg';
import l from '../images/l.jpg';
import m from '../images/m.jpg';
import n from '../images/n.jpg';
import img22 from '../images/22.jpg';
import img23 from '../images/23.jpg';
import img24 from '../images/24.jpg';
import img25 from '../images/25.jpg';
import img26 from '../images/26.jpg';
import img27 from '../images/27.jpg';

export const data = [a, b, c, d, e, g, i, j, k, l, m, n, img22, img23, img24, img25, img26, img27];
